### ISSUE TITLE
Some sort of issue.

### ISSUE THREAD

**Issue by pmow** [midgetspy/Lift-Cup#4]
I was testing lift_cup, and noticed a missing config file called ".newsmangler.conf", which I promptly created.  I'm wondering if this error is normal:

``` python
Calling Lift Cup for file /home/user/downloads/complete/Desperate.Housewives.S07E15.FRENCH.LD.HDTV.XViD-EPZ/epz-desperate.housewives.s07e15.nfo
Traceback (most recent call last):
  File "/home/user/lift_cup/lc.py", line 82, in <module>
    lc.lift_cup()
  File "/home/user/lift_cup/lift_cup.py", line 267, in lift_cup
    scene_file_name = self.make_scene_name(self.file)
  File "/home/user/lift_cup/lift_cup.py", line 242, in make_scene_name
    scene_name = scene_match.group(1) + '.' + scene_qualities[cur_quality] + '-' + scene_match.group(2) + extension
KeyError: 32768
```

**Comment by pmow** [comment]
My bad, I was calling the nfo file as well.
